version: '3.8'

services:
  database:
    platform: linux/amd64
    image: public.ecr.aws/lts/mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: Aec19cs047
      MYSQL_DATABASE: test
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3307:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 30s
      timeout: 10s
      retries: 5
    networks:
      - my_network

  auth-micro:
    platform: linux/amd64
    build:
      context: ./auth-micro
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: Aec19cs047
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
    networks:
      - my_network
    ports:
      - "8090:8090"
    depends_on:
      database:
        condition: service_healthy

  order-micro:
    platform: linux/amd64
    build:
      context: ./order-micro
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: Aec19cs047
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
    networks:
      - my_network
    ports:
      - "8091:8091"
    depends_on:
      database:
        condition: service_healthy

  restaurant-micro:
    platform: linux/amd64
    build:
      context: ./restaurant-micro
    environment:
      MYSQL_HOST: database
      MYSQL_USER: root
      MYSQL_PASSWORD: Aec19cs047
      MYSQL_DATABASE: test
      MYSQL_PORT: 3306
    networks:
      - my_network
    ports:
      - "8093:8093"
    depends_on:
      database:
        condition: service_healthy

volumes:
  mysql-data:

networks:
  my_network:
    driver: bridge
